
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 10 18:31:46 CST 2016
//----------------------------------------------------

package AnalizadorEjecucion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 4;
  public static final int COMA = 2;
  public static final int ENTERO = 8;
  public static final int EOF = 0;
  public static final int LLAVE_C = 7;
  public static final int LLAVE_A = 6;
  public static final int EJECUCION = 9;
  public static final int error = 1;
  public static final int PUNTOCOMA = 3;
  public static final int PROCESO = 10;
  public static final int PAR_C = 5;
}

