
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 10 16:29:09 CST 2016
//----------------------------------------------------

package AnalizadorSimulacion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 12;
  public static final int RECURSO = 3;
  public static final int COMA = 15;
  public static final int SIMULACION = 2;
  public static final int ENTERO = 16;
  public static final int R = 9;
  public static final int TERMINAR = 8;
  public static final int LLAVE_C = 11;
  public static final int EOF = 0;
  public static final int LIBERAR = 7;
  public static final int LLAVE_A = 10;
  public static final int error = 1;
  public static final int PUNTOCOMA = 14;
  public static final int ASIGNAR = 6;
  public static final int PAR_C = 13;
  public static final int TIEMPO = 4;
  public static final int PROCESO = 5;
}

